vich_uploader:
    db_driver: orm

    mappings:
        recipe_images:
            uri_prefix: '%app.path.website_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.website_images%'
            inject_on_load:     false
            delete_on_remove:   true
            delete_on_update:   true


